/**
 * This code was generated by Builder.io.
 */
import React from "react";
import BrokerItem from "./BrokerItem";

const brokers = [
  { id: 1, name: "Broker 1", amount: "Rs 600,000", status: "disconnected" },
  { id: 2, name: "Broker 2", amount: "Rs 800,000", status: "disconnected" },
  { id: 3, name: "Broker 3", amount: "Rs 40,00,000", status: "connected" },
];

function BrokerList() {
  return (
    <ul className="mt-7 max-md:bg-[#181916] max-md:mt-0">
      {brokers.map((broker) => (
        <li key={broker.id} className="mt-1 first:mt-0">
          <BrokerItem {...broker} />
        </li>
      ))}
    </ul>
  );
}

export default BrokerList;
