/**
 * This code was generated by Builder.io.
 */
import React from "react";

function BrokerItem({ name, amount, status }) {
  const buttonClass =
    status === "connected"
      ? "bg-lime-500 text-black"
      : "bg-pink-700 text-white";

  return (
    <div className="flex overflow-hidden flex-wrap gap-5 justify-between px-9 py-5 max-w-full rounded-xl border border-solid bg-stone-50 border-stone-300 w-[559px] max-md:px-5">
      <div className="flex flex-col self-start leading-none text-black">
        <div className="text-base font-bold">{name}</div>
        <div className="mt-1.5 text-xs max-md:mr-0.5">{amount}</div>
      </div>
      <button
        className={`gap-1 self-stretch px-3 py-2 text-base font-semibold leading-none text-center whitespace-nowrap rounded min-h-[36px] ${buttonClass}`}
      >
        {status === "connected" ? "Connect" : "Disconnect"}
      </button>
    </div>
  );
}

export default BrokerItem;
