/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ConnectionForm() {
  return (
    <form className="flex flex-col grow px-5 py-4 w-full text-base text-black bg-white rounded-lg  max-md:mt-10 max-md:max-w-full shadow-md card">
      <div className="flex flex-col w-full">
        <label htmlFor="apiKey">Api Key</label>
        <input
          id="apiKey"
          type="text"
          className="self-stretch px-5 py-3.5 mt-3 w-full whitespace-nowrap rounded-lg bg-stone-50 min-h-[52px]"
          value="567jd7ejd77jjhe"
          readOnly
        />
      </div>
      <div className="flex flex-col mt-5 max-w-full ">
        <label htmlFor="secretKey">Secret Key</label>
        <input
          id="secretKey"
          type="password"
          className="self-stretch px-5 py-3.5 mt-3 rounded-lg bg-stone-50 min-h-[52px]"
          value="*********************"
          readOnly
        />
        <p className="mt-3 text-xs leading-3 text-neutral-500">
          Add little bit helper text so user can easy complete this steps with
          ease
        </p>
      </div>
      <button
        type="submit"
        className="flex flex-col mt-5 w-full text-sm font-bold leading-none text-center text-black rounded "
      >
        <span className="gap-1 self-stretch px-7 py-5 bg-lime-500 rounded min-h-[50px] max-md:px-5">
          Start Connection
        </span>
      </button>
    </form>
  );
}

export default ConnectionForm;
