/**
 * This code was generated by Builder.io.
 */
import React from "react";

function BasketHeader() {
  return (
    <header className="flex overflow-hidden px-4 py-4 bg-white rounded-xl shadow-sm mb-5 basket-header">
      <div className="flex  gap-10 justify-between items-center mr-0 w-full max-md:flex-col-reverse">
        <div className="flex gap-7 self-stretch my-auto text-black min-h-[56px] min-w-[240px]">
          <div className="flex gap-3 h-full min-w-[240px]">
            <div className="flex shrink-0 my-auto h-14 bg-red-500 rounded-md w-[55px]" />
            <div className="flex flex-col">
              <div className="flex gap-1 items-end">
                <h1 className="text-md font-bold">Nifty50 JULFUT</h1>
                <span className="text-xs">NFO</span>
              </div>
              <div className="flex gap-4 items-end self-start mt-2">
                <div className="flex gap-1 items-center text-base font-bold w-[87px]">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/81e2c383663fe87021cdb8f72d72d7061429f443dfbeb75e3e0a45c41bea1777?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                    className="object-contain shrink-0 self-stretch my-auto w-3.5 aspect-square fill-lime-500"
                    alt=""
                  />
                  <span className="self-stretch my-auto">24815.77 </span>
                </div>
                <div className="flex gap-1 items-center text-sm font-semibold whitespace-nowrap">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/81e2c383663fe87021cdb8f72d72d7061429f443dfbeb75e3e0a45c41bea1777?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                    className="object-contain shrink-0 self-stretch my-auto w-3.5 aspect-square fill-lime-500"
                    alt=""
                  />
                  <span className="self-stretch my-auto">0.25%</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <form className="flex gap-3.5 self-start px-6 py-3.5 mt-1.5 text-base rounded-lg bg-stone-50 text-neutral-800 max-md:px-5 hidden-xs">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/d2290c4f96e9479ad8edf54630605c9692b71c7d901f8659d84f0314f34751a3?apiKey=b4d1b9e87b084579b1e2475047caf617&"
          className="object-contain shrink-0 self-start w-6 aspect-square"
          alt=""
        />
        <label htmlFor="searchInstruments" className="sr-only">
          Search Instruments
        </label>
        <input
          id="searchInstruments"
          type="text"
          placeholder="Search Instruments"
          className="flex-auto opacity-40 bg-transparent border-none"
        />
      </form>

        <div className="flex gap-1 items-center self-stretch my-auto min-w-[240px] max-md:max-w-full">
          <div className="flex flex-wrap gap-3 items-center self-stretch my-auto min-w-[240px] max-md:max-w-full bstatus">
            <div className="flex gap-1 items-center self-stretch my-auto">
              <span className="self-stretch my-auto text-xs text-neutral-500">
                Prev. Closed
              </span>
              <span className="self-stretch my-auto text-base font-bold text-black">
                190
              </span>
            </div>
            <div className="flex gap-1 items-center self-stretch my-auto whitespace-nowrap">
              <span className="self-stretch my-auto text-xs text-neutral-500">
                Open
              </span>
              <span className="self-stretch my-auto text-base font-bold text-black">
                188.16
              </span>
            </div>
            <div className="flex gap-1 items-center self-stretch my-auto whitespace-nowrap">
              <span className="self-stretch my-auto text-xs text-neutral-500">
                High
              </span>
              <span className="self-stretch my-auto text-base font-bold text-black">
                200
              </span>
            </div>
            <div className="flex gap-1 items-center self-stretch my-auto whitespace-nowrap">
              <span className="self-stretch my-auto text-xs text-neutral-500">
                Low
              </span>
              <span className="self-stretch my-auto text-base font-bold text-black">
                180
              </span>
            </div>
            <div className="flex gap-1 items-center self-stretch my-auto text-base font-bold text-black whitespace-nowrap">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/81e2c383663fe87021cdb8f72d72d7061429f443dfbeb75e3e0a45c41bea1777?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                className="object-contain shrink-0 self-stretch my-auto w-3.5 aspect-square fill-lime-500"
                alt=""
              />
              <span className="self-stretch my-auto">0.25%</span>
            </div>
            <div className="flex gap-1 items-center self-stretch my-auto whitespace-nowrap">
              <span className="self-stretch my-auto text-xs text-neutral-500">
                Volume
              </span>
              <span className="self-stretch my-auto text-base font-bold text-black">
                84.62M
              </span>
            </div>
          </div>
        </div>
      </div>
     
    </header>
  );
}

export default BasketHeader;
