/**
 * This code was generated by Builder.io.
 */
import React from "react";

function PendingOrders() {
  const orders = [
    {
      date: "12/12/2023",
      time: "11:25:32",
      instrument: "BankNifty 24 JUL26400PE",
      lot: "50",
      price: "700.70",
    },
    {
      date: "12/12/2023",
      time: "11:25:32",
      instrument: "BankNifty 24 JUL26400PE",
      lot: "50",
      price: "700.70",
    },
    {
      date: "1/20/2021",
      time: "10:39:30",
      instrument: "BankNifty 24 JUL22400PE",
      lot: "25",
      price: "600.70",
    },
    {
      date: "1/20/2021",
      time: "10:39:30",
      instrument: "BankNifty 24 JUL22400PE",
      lot: "25",
      price: "600.70",
    },
    {
      date: "3/9/2021",
      time: "10:20:20",
      instrument: "BankNifty 24 JUL23400PE",
      lot: "15",
      price: "400.70",
    },
    {
      date: "3/9/2021",
      time: "10:20:20",
      instrument: "BankNifty 24 JUL23400PE",
      lot: "15",
      price: "400.70",
    },
    {
      date: "1/12/2021",
      time: "9:20:20",
      instrument: "BankNifty 24 JUL23400PE",
      lot: "05",
      price: "300.70",
    },
    {
      date: "1/12/2021",
      time: "9:20:20",
      instrument: "BankNifty 24 JUL23400PE",
      lot: "05",
      price: "300.70",
    },
  ];

  return (
    <div className="flex overflow-hidden flex-col items-start px-6 pt-6 pb-20 mx-auto w-full bg-white rounded-xl max-md:pl-5 max-md:mt-1">
      <div className="flex gap-2 items-center text-xs font-semibold leading-none text-center">
        <button className="gap-2.5 self-stretch px-4 py-2 my-auto rounded bg-lime-500 bg-opacity-40 text-stone-950">
          Pending Orders
        </button>
        <button className="self-stretch my-auto text-stone-400">
          Completed Orders
        </button>
      </div>
      <div className="flex gap-5 justify-between mt-6 max-w-full text-xs leading-none text-neutral-500 w-[265px]">
        <div className="text-center">Time</div>
        <div className="text-center">Instrument</div>
        <div className="flex gap-7 self-start">
          <div>Lot</div>
          <div className="text-center">Price (Rs)</div>
        </div>
      </div>
      <div className="flex gap-4 self-stretch mt-4">
        <div className="flex flex-auto gap-3 text-xs leading-3 text-neutral-800">
          <div className="flex flex-col">
            {orders.map((order, index) => (
              <div key={index} className={index > 0 ? "mt-4" : ""}>
                {order.date} <br /> {order.time}
              </div>
            ))}
          </div>
          <div className="flex flex-col">
            {orders.map((order, index) => (
              <div key={index} className={index > 0 ? "mt-4" : ""}>
                {order.instrument}
              </div>
            ))}
          </div>
          <div className="flex flex-col justify-between my-auto leading-none whitespace-nowrap min-h-[303px] max-md:hidden">
            {orders.map((order, index) => (
              <div key={index}>{order.lot}</div>
            ))}
          </div>
          <div className="flex flex-col justify-between mt-1.5 leading-none whitespace-nowrap min-h-[303px]">
            {orders.map((order, index) => (
              <div key={index} className={index > 0 ? "mt-7" : ""}>
                {order.price}
              </div>
            ))}
          </div>
        </div>
        <div className="flex gap-1.5">
          <div className="flex flex-col justify-between min-h-[309px] max-md:hidden">
            {orders.map((_, index) => (
              <button
                key={index}
                className="flex gap-1 justify-center items-center px-1.5 rounded border border-solid border-neutral-800 h-[22px] min-h-[22px] w-[22px]"
              >
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/7b83be3621bda90d157ad230475b85a84e1cc12006c1520afb77aa92b99f9262?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                  className="object-contain self-stretch my-auto w-3 aspect-square"
                  alt=""
                />
              </button>
            ))}
          </div>
          <div className="flex flex-col justify-between min-h-[309px] max-md:hidden">
            {orders.map((_, index) => (
              <button
                key={index}
                className="flex gap-1 justify-center items-center px-1.5 bg-pink-700 rounded h-[22px] min-h-[22px] w-[22px]"
              >
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/f11074d587c0741cc95b02137e46997b96c52aaf40e19a07f76545695290fff9?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                  className="object-contain self-stretch my-auto w-3 aspect-square"
                  alt=""
                />
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export default PendingOrders;
