/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TradeForm() {
  return (
    <div className="flex overflow-hidden flex-col px-5 py-8 mt-1.5 w-full bg-white rounded-xl">
      <h2 className="self-start text-xl font-bold leading-none text-black">
        Nifty Commodity
      </h2>
      <div className="flex gap-5 justify-between mt-6 w-full leading-none whitespace-nowrap">
        <div className="flex overflow-hidden gap-1.5 items-center px-3 py-2 bg-white rounded-md border border-black border-solid min-h-[30px]">
          <div className="flex gap-1 items-end self-stretch my-auto">
            <span className="text-xs font-semibold text-neutral-800">
              Overnight
            </span>
            <span className="text-xs text-neutral-500">NRML</span>
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/fc5c5b3287a2e83fd9b1613262e9bd66e1b0ec44fac0bf2500e108c7eb5d5b8c?apiKey=b4d1b9e87b084579b1e2475047caf617&"
            className="object-contain shrink-0 self-stretch my-auto w-3.5 aspect-square"
            alt=""
          />
        </div>
        <button className="flex overflow-hidden gap-6 justify-end py-1 pr-1 pl-2.5 my-auto text-xs font-bold text-black bg-lime-500 rounded-2xl border border-black border-solid">
          <span className="my-auto">Buy</span>
          <div className="flex shrink-0 bg-white rounded-full fill-white h-[18px] w-[18px]" />
        </button>
      </div>
      <div className="flex gap-3 mt-6">
        <div className="flex flex-col flex-1">
          <label
            htmlFor="lotQty"
            className="flex gap-5 justify-between items-end max-w-full leading-none w-[140px]"
          >
            <span className="text-xs font-semibold text-neutral-800">
              Lot Qty
            </span>
            <span className="text-xs text-black">1 lot = 25 shares</span>
          </label>
          <input
            type="number"
            id="lotQty"
            className="flex gap-5 justify-between px-5 py-1 mt-2 max-w-full whitespace-nowrap rounded-md bg-stone-50 text-neutral-800 w-[140px]"
            defaultValue="1"
          />
        </div>
        <div className="flex flex-col flex-1 whitespace-nowrap">
          <label
            htmlFor="price"
            className="flex gap-6 justify-between items-end w-full leading-none max-w-[129px]"
          >
            <span className="text-xs font-semibold text-neutral-800">
              Price
            </span>
            <div className="flex gap-1.5 items-center text-xs text-black">
              <button className="flex gap-0.5 items-center self-stretch my-auto">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/8053dd03aa5bdcbad399e663c5bdc79939443efcc6295da43d555ec9892f7a1b?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                  className="object-contain shrink-0 self-stretch my-auto w-3 aspect-square"
                  alt=""
                />
                <span className="self-stretch my-auto">Mkt</span>
              </button>
              <button className="flex gap-0.5 items-center self-stretch my-auto">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/11aa68f26b96f98733a0da8e4b7f535d633af5d0cba973126aeaaea72967b616?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                  className="object-contain shrink-0 self-stretch my-auto w-3 aspect-square"
                  alt=""
                />
                <span className="self-stretch my-auto">Limit</span>
              </button>
            </div>
          </label>
          <input
            type="number"
            id="price"
            className="flex flex-col justify-center items-start px-3 py-1.5 mt-2 max-w-full text-sm rounded-md bg-stone-50 text-neutral-800 w-[129px]"
            placeholder="00"
          />
        </div>
      </div>
      <div className="flex flex-col mt-5 max-w-full whitespace-nowrap w-[140px]">
        <label
          htmlFor="trigger"
          className="flex gap-8 justify-between items-end w-full leading-none max-w-[140px]"
        >
          <span className="text-xs font-semibold text-neutral-800">
            Trigger
          </span>
          <div className="flex gap-1.5 items-center text-xs text-black">
            <button className="flex gap-0.5 items-center self-stretch my-auto">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/8053dd03aa5bdcbad399e663c5bdc79939443efcc6295da43d555ec9892f7a1b?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                className="object-contain shrink-0 self-stretch my-auto w-3 aspect-square"
                alt=""
              />
              <span className="self-stretch my-auto">SL</span>
            </button>
            <button className="flex gap-0.5 items-center self-stretch my-auto">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/11aa68f26b96f98733a0da8e4b7f535d633af5d0cba973126aeaaea72967b616?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                className="object-contain shrink-0 self-stretch my-auto w-3 aspect-square"
                alt=""
              />
              <span className="self-stretch my-auto">SL-M</span>
            </button>
          </div>
        </label>
        <input
          type="number"
          id="trigger"
          className="flex gap-5 justify-between px-5 py-1 mt-2 w-full rounded-md bg-stone-50 text-neutral-800"
          defaultValue="1"
        />
      </div>
      <div className="flex gap-3.5">
        <div className="flex flex-col self-start mt-5">
          <div className="flex gap-3 whitespace-nowrap text-neutral-800 max-md:mr-1">
            <div className="flex flex-col flex-1">
              <label
                htmlFor="stopLoss"
                className="flex gap-0.5 items-center text-xs font-semibold leading-none"
              >
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/872fcba766292a479bfe213bbf0e6ece176a4b3c9e87f7b7d557266e9219f4f2?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                  className="object-contain shrink-0 self-stretch my-auto w-2 aspect-square"
                  alt=""
                />
                <span className="gap-3 self-stretch my-auto">StopLoss</span>
              </label>
              <input
                type="number"
                id="stopLoss"
                className="flex flex-col justify-center items-start px-10 py-1.5 mt-2 w-16 text-sm rounded-md bg-stone-50 max-md:pl-5"
                placeholder="%"
              />
            </div>
            <div className="flex flex-col flex-1">
              <label
                htmlFor="target"
                className="flex gap-0.5 items-center self-start text-xs font-semibold leading-none"
              >
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/872fcba766292a479bfe213bbf0e6ece176a4b3c9e87f7b7d557266e9219f4f2?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                  className="object-contain shrink-0 self-stretch my-auto w-2 aspect-square"
                  alt=""
                />
                <span className="gap-3 self-stretch my-auto">Target</span>
              </label>
              <input
                type="number"
                id="target"
                className="flex flex-col justify-center items-start px-10 py-1.5 mt-2 w-16 text-sm rounded-md bg-stone-50 max-md:pl-5"
                placeholder="%"
              />
            </div>
          </div>
          <div className="flex items-center mt-5 leading-none">
            <span className="self-stretch my-auto text-xs text-neutral-500 w-[50px]">
              Charges
            </span>
            <span className="self-stretch my-auto text-sm font-semibold text-black w-[76px]">
              Rs 534,656
            </span>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/2b0a91bfc154a28559273a97c325785acbe1d5d6b1857d8627ae9b082dded786?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              className="object-contain shrink-0 self-stretch my-auto w-3.5 aspect-square"
              alt=""
            />
          </div>
        </div>
        <div className="flex flex-col leading-none">
          <div className="flex gap-3 items-end text-sm font-bold text-center">
            <div className="flex flex-col justify-center w-[123px]">
              <button className="gap-1 self-stretch px-7 py-2 max-w-full whitespace-nowrap bg-lime-500 rounded min-h-[30px] text-stone-950 w-[123px] max-md:px-5">
                Buy
              </button>
              <button className="gap-1 self-stretch px-7 py-2 mt-2 max-w-full rounded border border-solid border-neutral-800 min-h-[30px] text-neutral-800 w-[123px] max-md:px-5">
                To basket
              </button>
            </div>
          </div>
          <div className="flex gap-2 items-start mt-5 max-md:mr-2 max-md:ml-2.5">
            <span className="text-xs text-neutral-500">Margin</span>
            <span className="text-sm font-semibold text-black">Rs 53461</span>
          </div>
        </div>
      </div>
    </div>
  );
}

export default TradeForm;
