import { Inter } from "next/font/google";
import "./globals.css";
import "../assets/icons/style.css";
// import "@sjmc11/tourguidejs/src/scss/tour.scss";
// import { TourGuideClient } from "@sjmc11/tourguidejs/src/Tour";
// import { TourGuideClient } from "@sjmc11/tourguidejs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
