/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ActionButton = ({ type }) => {
  if (type === "copy") {
    return (
      <div className="flex gap-4 items-center self-stretch my-auto text-sm font-bold text-center text-stone-950">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/965f90b34354dbfdde0126edc069b1e895cdee7c30589d01ca89d28feee41a85?apiKey=b4d1b9e87b084579b1e2475047caf617&"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto aspect-[1.2] fill-pink-700 stroke-[1px] stroke-stone-950 w-[18px]"
        />
        <button className="gap-2 self-stretch p-3 my-auto bg-lime-500 rounded min-h-[38px] w-[76px]">
          Copy
        </button>
      </div>
    );
  } else if (type === "stopPause") {
    return (
      <div className="flex gap-4 items-center self-stretch my-auto text-sm font-bold text-center">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/965f90b34354dbfdde0126edc069b1e895cdee7c30589d01ca89d28feee41a85?apiKey=b4d1b9e87b084579b1e2475047caf617&"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto aspect-[1.2] fill-pink-700 stroke-[1px] stroke-stone-950 w-[18px]"
        />
        <div className="flex gap-1 items-center self-stretch my-auto">
          <button className="gap-2 self-stretch p-3 my-auto w-16 text-white bg-pink-700 rounded min-h-[38px]">
            Stop
          </button>
          <button className="gap-2 self-stretch py-3 pr-3 pl-3 my-auto w-16 rounded border border-solid border-neutral-800 min-h-[38px] text-neutral-800">
            Pause
          </button>
        </div>
      </div>
    );
  }
};

export default ActionButton;
