/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Chart = ({ data, period }) => {
  return (
    <div className="flex flex-col text-xs text-center text-stone-400 w-[105px]">
      <img
        loading="lazy"
        src={data}
        alt={`Performance chart for last ${period}`}
        className="object-contain self-center rounded-sm aspect-[1.86] w-[89px]"
      />
      <div className="mt-3.5">Last {period}</div>
    </div>
  );
};

export default Chart;
