/**
 * This code was generated by Builder.io.
 */
import React from "react";
import DashboardIcons from "./DashboardIcons";
import PnLCurve from "./PnLCurve";
import CurrentLivePosition from "./CurrentLivePosition";
import StrategiesFollowed from "./StrategiesFollowed";
import TransactionHistory from "./TransactionHistory";
import TopTraders from "./TopTraders";

function MainContent() {
  return (
    <main className="main-container">
      <div className="my-5">
        <DashboardIcons />

        <div className="flex  gap-5 justify-between items-center self-center mt-10">
          <PnLCurve />
          <CurrentLivePosition />
        </div>
      </div>

      <div className="my-5">
      <div className="flex align-center justify-between mt-10 mb-5">
        <div className="self-start text-xl font-bold leading-none text-neutral-800">
          Strategies you follow
        </div>

        <a href="/copy-trading/leader-board/" className="overflow-hidden z-10 gap-1.5 self-end px-3 py-1.5 -mt-6 text-xs font-semibold rounded border border-solid border-neutral-800 min-h-[24px] text-neutral-800">
          View More
        </a>
      </div>

        <StrategiesFollowed />
      </div>
      <div className="my-5">
        <TopTraders />
      </div>
      <div className="my-5">
        <TransactionHistory />
      </div>
    </main>
  );
}

export default MainContent;
