/**
 * This code was generated by Builder.io.
 */
import React from "react";

function InputField({ label, placeholder }) {
  return (
    <div className="flex flex-col mt-12 max-w-full text-base text-neutral-800 w-[393px] max-md:mt-10">
      <label className="font-bold leading-none opacity-80">{label}</label>
      <div>
        <input
          type="text"
          placeholder={placeholder}
          className="w-full  opacity-40 px-5 py-3.5 mt-3 w-full rounded-lg bg-stone-100 border border-stone-500"
          aria-label={label}
        />
      </div>
    </div>
  );
}

export default InputField;
