/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className="flex flex-wrap items-center px-16 pt-3 pb-3.5 w-full border-b border-solid bg-stone-950 border-b-neutral-800 max-md:px-5 max-md:max-w-full">
      <div className="self-stretch my-auto text-base font-black text-lime-500 w-[58px]">
        SPEDIT
      </div>
      <div className="flex flex-col flex-1 shrink justify-center items-center self-stretch pl-8 my-auto text-base whitespace-nowrap basis-0 min-w-[240px] text-neutral-500 max-md:max-w-full">
        <div className="flex gap-4 justify-between items-start w-[91px]">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/236c2f2a224a9f91bae67ba81d33f8bda2f0f7291e9fff1454bf2f90daf16dfc?apiKey=b4d1b9e87b084579b1e2475047caf617&"
            alt=""
            className="object-contain shrink-0 w-6 aspect-square"
          />
          <div>Search</div>
        </div>
      </div>
      <div className="flex gap-4 justify-center items-center self-stretch my-auto text-sm leading-none text-center text-white">
        <div className="overflow-hidden gap-2 self-stretch px-3 py-1 my-auto rounded-md shadow-lg bg-lime-500 bg-opacity-30">
          50 Credits
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/2b7026479bb1d29337ab0c0af737db7dbfc242bfd7657a58c06faae68fd689ef?apiKey=b4d1b9e87b084579b1e2475047caf617&"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
        />
      </div>
    </header>
  );
}

export default Header;
