/**
 * This code was generated by Builder.io.
 */
import React from "react";
import DashboardIcons from "./DashboardIcons";
import PnLCurve from "./PnLCurve";
import CurrentLivePosition from "./CurrentLivePosition";
import StrategiesFollowed from "./StrategiesFollowed";
import TransactionHistory from "./TransactionHistory";
import TopTraders from "./TopTraders";

function MainContent() {
  return (
    <main className="flex flex-col ml-5 w-4/5 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col w-full max-md:max-w-full">
        <DashboardIcons />
        <div className="flex flex-wrap gap-5 justify-between items-center self-center mt-16 w-full leading-none h-[547px] max-w-[1129px] max-md:mt-10 max-md:max-w-full">
          <PnLCurve />
          <CurrentLivePosition />
        </div>
      </div>
      <div className="flex flex-col self-end mt-0 mr-20 w-full max-w-[1129px] max-md:mr-2.5 max-md:max-w-full">
        <StrategiesFollowed />
        <TopTraders />
        <TransactionHistory />
      </div>
    </main>
  );
}

export default MainContent;
