/**
 * This code was generated by Builder.io.
 */
import React from "react";
import DashboardIcons from "./DashboardIcons";
import PnLCurve from "./PnLCurve";
import CurrentLivePosition from "./CurrentLivePosition";
import StrategiesFollowed from "./StrategiesFollowed";
import TransactionHistory from "./TransactionHistory";
import TopTraders from "./TopTraders";

function MainContent() {
  return (
    <main style={{ marginTop: "-2rem" }} className="main-container">
      <div className="my-5">
        <DashboardIcons />

        <div className="flex flex-wrap gap-5 justify-between items-center self-center mt-10 px-16">
          <PnLCurve />
          <CurrentLivePosition />
        </div>
      </div>

      <div className="my-5">
        <StrategiesFollowed />
      </div>
      <div className="my-5">
        <TopTraders />
      </div>
      <div className="my-5">
        <TransactionHistory />
      </div>
    </main>
  );
}

export default MainContent;
