/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TraderCard from "./TraderCard";

const traders = [
  {
    name: "Karishma",
    rating: 502,
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/7c62b7d3f937fbd4b1613119320479795c50ea47f5855156f0fa337c0804bc40?apiKey=b4d1b9e87b084579b1e2475047caf617&",
    pnl: 74100.23,
    roi: 5.71,
    aum: 74100.23,
    mdd: 1.27,
    chart:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9638977b79520c79b984b2ea7f5f5a81fc921e1fe4033ba4df38c7d1208476fa?apiKey=b4d1b9e87b084579b1e2475047caf617&",
  },
  {
    name: "Karishma",
    rating: 502,
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/7c62b7d3f937fbd4b1613119320479795c50ea47f5855156f0fa337c0804bc40?apiKey=b4d1b9e87b084579b1e2475047caf617&",
    pnl: 74100.23,
    roi: 5.71,
    aum: 74100.23,
    mdd: 1.27,
    chart:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/af0dfeea4f2bbc6ca552fab915ffb1dc9e916b0ba4cea1195b525f05ce4e9fc4?apiKey=b4d1b9e87b084579b1e2475047caf617&",
  },
  {
    name: "Karishma",
    rating: 502,
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/7c62b7d3f937fbd4b1613119320479795c50ea47f5855156f0fa337c0804bc40?apiKey=b4d1b9e87b084579b1e2475047caf617&",
    pnl: 74100.23,
    roi: 5.71,
    aum: 74100.23,
    mdd: 1.27,
    chart:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/8ca195bebca423d8768a392c72bc0a551c90747904d29bdefc14f3e449d12571?apiKey=b4d1b9e87b084579b1e2475047caf617&",
  },
];

function TopTraders() {
  return (
    <section className="flex flex-col mt-20 w-full max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-col justify-center w-full max-md:max-w-full">
        <div className="flex flex-wrap gap-10 justify-between items-center w-full text-neutral-800 max-md:max-w-full">
          <h2 className="self-stretch my-auto text-xl font-bold leading-none w-[270px]">
            Top traders of the week
          </h2>
          <button className="overflow-hidden gap-1.5 self-stretch px-4 py-1.5 my-auto text-xs font-semibold rounded border border-solid border-neutral-800 min-h-[24px] w-[72px]">
            View All
          </button>
        </div>
        <div className="flex flex-wrap gap-6 items-center mt-6 w-full leading-none max-md:max-w-full">
          {traders.map((trader, index) => (
            <TraderCard key={index} {...trader} />
          ))}
        </div>
        <div className="flex gap-6 justify-center items-center self-center mt-6 w-5">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/3df10dab7f593cccc2d04679f42f44261d40110d12914a1adca69b322e4f2f7b?apiKey=b4d1b9e87b084579b1e2475047caf617&"
            alt=""
            className="object-contain shrink-0 self-stretch my-auto w-5 rounded-none aspect-square"
          />
          <div className="flex flex-col justify-center self-stretch my-auto rotate-[-1.570796370506285rad]">
            <div className="flex w-full rounded-full bg-neutral-800 fill-neutral-800 min-h-[12px]" />
            <div className="flex self-center mt-4 w-full rounded-full bg-neutral-800 fill-neutral-800 min-h-[12px]" />
            <div className="flex self-end mt-4 w-full bg-lime-500 rounded-full fill-lime-500 min-h-[12px]" />
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e56daf61941313c9c29b1320b0f271ec10c2821bf2e4ac8944575eb5b68ed6f3?apiKey=b4d1b9e87b084579b1e2475047caf617&"
            alt=""
            className="object-contain shrink-0 self-stretch my-auto rounded-none aspect-[1.05] w-[21px]"
          />
        </div>
      </div>
    </section>
  );
}

export default TopTraders;
