/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TransactionRow from "./TransactionRow";

const transactions = [
  {
    id: "12345i",
    time: "2024-07-08-10:21:06",
    price: 104.45,
    quantity: 536,
    instrument: "Nifty Fut",
    strategyId: 50963,
    realizedProfit: 1439,
  },
  {
    id: "12345i",
    time: "2024-07-08-10:21:06",
    price: 740,
    quantity: 703,
    instrument: "Nifty 24500 CE",
    strategyId: 33981,
    realizedProfit: -4349,
  },
  {
    id: "12345i",
    time: "2024-07-08-10:21:06",
    price: 600,
    quantity: 447,
    instrument: "Nifty 24500 CE",
    strategyId: 95554,
    realizedProfit: 9261,
  },
  {
    id: "12345i",
    time: "2024-07-08-10:21:06",
    price: 556,
    quantity: 423,
    instrument: "Nifty 24500 PE",
    strategyId: 13671,
    realizedProfit: 1784,
  },
  {
    id: "12345i",
    time: "2024-07-08-10:21:06",
    price: 196,
    quantity: 492,
    instrument: "Nifty Fut",
    strategyId: 10708,
    realizedProfit: 8811,
  },
  {
    id: "12345i",
    time: "2024-07-08-10:21:06",
    price: 922,
    quantity: 154,
    instrument: "Nifty 24500 CE",
    strategyId: 83676,
    realizedProfit: -4152,
  },
];

function TransactionHistory() {
  return (
    <section className="mt-16 max-md:mt-10 max-md:mr-2.5 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-between items-end w-full text-neutral-800">
        <h2 className="text-xl font-bold leading-none w-[270px]">
          Transaction History
        </h2>
        <button className="overflow-hidden gap-1.5 self-stretch py-1.5 pr-2.5 pl-3 text-xs font-semibold rounded border border-solid border-neutral-800 min-h-[24px] w-[99px]">
          View Full history
        </button>
      </div>
      <div className="flex overflow-hidden flex-col mt-6 w-full text-sm leading-none bg-white rounded-xl shadow-sm h-[341px] text-neutral-800 max-md:mr-1.5 max-md:max-w-full">
        <div className="flex flex-wrap items-center w-full text-base font-bold leading-none text-lime-500 min-h-[61px] max-md:max-w-full">
          <div className="flex gap-1 justify-center items-center self-stretch p-6 my-auto w-36 border-r border-b border-solid bg-neutral-800 border-b-zinc-300 border-r-zinc-300 min-h-[60px] max-md:px-5">
            <div className="self-stretch my-auto">Trade ID</div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/9d930045102bfd8e0f6f35da8fb92f2b3f339a0a3844c9c7d89b1a62e370b7fb?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-2.5 aspect-square"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/6222a04d8b16e66c8154559f53c6e36c0680cb33b13cce5e30e6d2d1fb32d84e?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-3.5 aspect-square"
            />
          </div>
          <div className="flex gap-1 justify-center items-center self-stretch p-6 my-auto w-48 whitespace-nowrap border-r border-b border-solid bg-neutral-800 border-b-zinc-300 border-r-zinc-300 min-h-[60px] max-md:px-5">
            <div className="self-stretch my-auto">Time</div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/6422a143bb9b81f6caf9e29a35ef7e5597254740308feb18f629945b0b70e604?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-2.5 aspect-square"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/6222a04d8b16e66c8154559f53c6e36c0680cb33b13cce5e30e6d2d1fb32d84e?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-3.5 aspect-square"
            />
          </div>
          <div className="flex gap-1 justify-center items-center self-stretch p-6 my-auto whitespace-nowrap border-r border-b border-solid bg-neutral-800 border-b-zinc-300 border-r-zinc-300 min-h-[60px] w-[124px] max-md:px-5">
            <div className="self-stretch my-auto">Price</div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/cb08aba0a42611a98211670133703ebf4eb1a5bc79525a3ec8f79d7a4f775839?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-2.5 aspect-square"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/6222a04d8b16e66c8154559f53c6e36c0680cb33b13cce5e30e6d2d1fb32d84e?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-3.5 aspect-square"
            />
          </div>
          <div className="flex gap-1 items-center self-stretch p-6 my-auto w-36 whitespace-nowrap border-r border-b border-solid bg-neutral-800 border-b-zinc-300 border-r-zinc-300 min-h-[60px] max-md:px-5">
            <div className="self-stretch my-auto">Quantity</div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/4c086b6c816a93ce74f7b7a7ebc3b54367d99cf26ebcc2087c5e09337b643cfd?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-2.5 aspect-square"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/adce928802fc074a5d3bb67605171e7a3553812f8e67e34a713ac1964d2eb81f?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-3.5 aspect-square"
            />
          </div>
          <div className="flex gap-1 justify-center items-center self-stretch px-1.5 py-6 my-auto whitespace-nowrap border-r border-b border-solid bg-neutral-800 border-b-zinc-300 border-r-zinc-300 w-[154px]">
            <div className="self-stretch my-auto">Instrument</div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d0dfb23ea60bc3961b0e0425ee8b70338aeb1ba75205f232121029783899dd61?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-2.5 aspect-square"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/6222a04d8b16e66c8154559f53c6e36c0680cb33b13cce5e30e6d2d1fb32d84e?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-3.5 aspect-square"
            />
          </div>
          <div className="flex gap-1 justify-center items-center self-stretch py-6 pr-5 pl-5 my-auto border-r border-b border-solid bg-neutral-800 border-b-zinc-300 border-r-zinc-300 min-h-[59px] w-[155px]">
            <div className="self-stretch my-auto">Strategy ID</div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/9d13afc601143a2073a4a343ef2559b4600b99ac0ea3070a903a0336dceb3f0b?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-2.5 aspect-square"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/6222a04d8b16e66c8154559f53c6e36c0680cb33b13cce5e30e6d2d1fb32d84e?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-3.5 aspect-square"
            />
          </div>
          <div className="flex gap-1 justify-center items-center self-stretch px-6 py-5 my-auto w-52 border-r border-b border-solid bg-neutral-800 border-b-zinc-300 border-r-zinc-300 min-h-[59px] max-md:px-5">
            <div className="self-stretch my-auto">Realized Profit</div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f384b7a3e6faba2f340d53d36bd7f6724d07627009517810d1cfe5016ea03da8?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto aspect-square w-[18px]"
            />
          </div>
        </div>
        {transactions.map((transaction, index) => (
          <TransactionRow key={index} {...transaction} />
        ))}
      </div>
    </section>
  );
}

export default TransactionHistory;
