/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TransactionRow({
  id,
  time,
  price,
  quantity,
  instrument,
  strategyId,
  realizedProfit,
}) {
  const profitClass = realizedProfit >= 0 ? "text-lime-500" : "text-pink-600";

  return (
    <div className="flex overflow-hidden flex-wrap items-center w-full h-14 max-md:max-w-full">
      <div className="overflow-hidden grow shrink gap-1.5 self-stretch px-6 py-9 my-auto font-semibold leading-none text-blue-500 whitespace-nowrap bg-white border-r border-b border-solid border-b-zinc-300 border-r-zinc-300 min-h-[82px] w-[119px] max-md:px-5">
        {id}
      </div>
      <div className="overflow-hidden grow shrink gap-2.5 self-stretch px-3 py-8 my-auto whitespace-nowrap bg-white border-r border-b border-solid border-b-zinc-300 border-r-zinc-300 min-h-[82px] w-[167px]">
        {time}
      </div>
      <div className="overflow-hidden grow shrink gap-2.5 self-stretch px-3 py-8 my-auto whitespace-nowrap bg-white border-r border-b border-solid border-b-zinc-300 border-r-zinc-300 min-h-[82px] w-[98px]">
        {price}
      </div>
      <div className="overflow-hidden grow shrink gap-2.5 self-stretch px-6 py-8 my-auto whitespace-nowrap bg-white border-r border-b border-solid border-b-zinc-300 border-r-zinc-300 min-h-[82px] w-[119px] max-md:px-5">
        {quantity}
      </div>
      <div className="overflow-hidden grow shrink gap-2.5 self-stretch px-5 py-8 my-auto bg-white border-r border-b border-solid border-b-zinc-300 border-r-zinc-300 min-h-[82px] w-[130px]">
        {instrument}
      </div>
      <div className="overflow-hidden grow shrink gap-2.5 self-stretch px-5 py-8 my-auto whitespace-nowrap bg-white border-r border-b border-solid border-b-zinc-300 border-r-zinc-300 min-h-[82px] w-[129px]">
        {strategyId}
      </div>
      <div
        className={`overflow-hidden grow shrink gap-2.5 self-stretch px-5 py-9 my-auto font-semibold leading-none whitespace-nowrap bg-white border-r border-b border-solid border-b-zinc-300 border-r-zinc-300 min-h-[82px] w-[183px] ${profitClass}`}
      >
        {realizedProfit}
      </div>
    </div>
  );
}

export default TransactionRow;
