/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SectionHeader from "./SectionHeader";
import InputField from "./InputField";

function EmbedVideoSection() {
  return (
    <section className="flex card flex-col px-12 py-9 mt-3 w-full bg-white rounded-xl max-md:px-5 max-md:max-w-full">
      <SectionHeader
        title="Embed Video"
        description="Share from Adobe XD, Vimeo, YouTube, GIPHY, SoundCloud, Spotify and more"
      />
      <div className="mt-14 max-md:mt-10 max-md:mr-2 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[45%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col w-full text-base text-neutral-800 max-md:mt-10">
              <InputField
                label="Enter Video Title"
                placeholder="Eg: Video Title"
              />
              <div className="flex flex-col mt-12 font-bold leading-none max-md:mt-10">
                <label className="opacity-80">Paste Embed Code</label>
                <textarea
                  className="flex mt-3 max-w-full rounded-lg bg-stone-50 min-h-[169px] w-[393px] p-3"
                  aria-label="Paste Embed Code"
                />
              </div>
              <button className="gap-2 self-start px-3 py-4 mt-3 text-sm font-bold leading-none text-center whitespace-nowrap rounded border border-solid border-neutral-800 min-h-[44px]">
                Embed
              </button>
            </div>
          </div>
          <div className="flex flex-col ml-5 w-[55%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col mt-3.5 text-base font-bold leading-none whitespace-nowrap text-neutral-800 max-md:mt-10 max-md:max-w-full">
              <h3 className="self-start opacity-80">Preview</h3>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/9af50911f16ac93a26212a8e896cb2fcc9a98fbf6fcb348ddbe0155f93f724ff?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                alt="Video preview"
                className="object-contain mt-2.5 w-full rounded-none aspect-[1.68] max-md:max-w-full"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default EmbedVideoSection;
