/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SectionHeader({ title, description }) {
  return (
    <div className="flex justify-between items-center leading-none">
      <div className="flex flex-col self-stretch my-auto min-w-[240px]">
        <h2 className="text-xl font-bold opacity-80 text-stone-950">{title}</h2>
        <p className="mt-2 text-xs text-neutral-500">{description}</p>
      </div>
    </div>
  );
}

export default SectionHeader;
