/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function SideBar() {
  return (
    <aside className="flex flex-col w-1/5 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col items-center py-12 pr-9 mx-auto w-full text-xl bg-stone-950">
        <div className="flex gap-7 items-start leading-7 text-neutral-500">
          <div className="w-[126px]">
            Welcome, <br />
            <span className="font-bold">Admin</span>
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/19d1e92fb6347c89988027fcb4987c4cdad97a9ac9e64508a541925bccd8e7bd?apiKey=b4d1b9e87b084579b1e2475047caf617&"
            alt="Admin Avatar"
            className="object-contain shrink-0 w-14 aspect-square"
          />
        </div>
        <nav className="flex gap-10 self-start mt-14 font-semibold text-white max-md:mt-10">
          <div className="flex shrink-0 self-start w-1 h-10 bg-lime-500"></div>
          <ul className="flex flex-col">
            <li className="flex relative gap-2 items-center w-full text-lime-500">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/07cbebe704fd901358c9d93909d1995959480f0ec4374f673c7cf028202aa537?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                alt=""
                className="object-contain z-0 shrink-0 self-stretch my-auto w-6 aspect-square"
              />
              <div className="z-0 my-auto w-[145px]">User management</div>
              <div className="flex absolute top-2/4 z-0 shrink-0 self-start w-1 -translate-y-2/4 h-[43px] left-[-57px] translate-x-[0%]"></div>
            </li>
            <li className="flex gap-2 items-start mt-6">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/f8d122d066abf806f573b9bfabd4bf400d68c12b19e9ce3e0a3faab477b9f354?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                alt=""
                className="object-contain shrink-0 w-6 aspect-square"
              />
              <div className="w-[183px]">Transaction Monitor</div>
            </li>
            <li className="flex gap-2 items-center mt-6 w-full text-white whitespace-nowrap">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/ba6bce118842a5f25458fe422490b93dd17bccad9ca768a47e2ca2881b5079e9?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              />
              <div className="self-stretch my-auto w-[188px]">CMS</div>
            </li>
            <li className="flex gap-2 items-center mt-6 w-full text-white">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/24dc29dea0016cf72bd3e640f94e5c6d2c97b6ff8d0d907f3e9aa36768fe334f?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              />
              <div className="my-auto w-[136px]">Analytics & Reporting</div>
            </li>
            <li className="flex gap-2 items-start mt-6 w-full text-white">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/98fdf82ca89fbf54be06132b591db23bf4c49642e9381cdb3f89f2de946ef805?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                alt=""
                className="object-contain shrink-0 w-6 aspect-square"
              />
              <div className="flex-1 shrink basis-0">Marketing Tools</div>
            </li>
            <li className="flex gap-2 items-center mt-6 w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/17438ed4cfd1e932d19317e9395cc7a822e844094da5592226118631b5cf80cb?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              />
              <div className="flex-1 shrink self-stretch my-auto basis-0">
                Support & Ticketing
              </div>
            </li>
            <li className="flex gap-2 items-center mt-6 w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/f3a1eef466e3e1f61d5bddd18305a5119452307101a6377ec397ecb8026996b1?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              />
              <div className="self-stretch my-auto w-[191px]">
                Rights Management
              </div>
            </li>
            <li className="flex gap-2 items-center mt-6 w-full whitespace-nowrap">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/6068a9676a36e06dbc236e639befb13d1c631608d5da829f8ed6107e1b56ee0e?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              />
              <div className="self-stretch my-auto w-[191px]">Trash</div>
            </li>
          </ul>
        </nav>
        <div className="flex flex-col mt-36 max-w-full text-xs text-center text-neutral-500 w-[233px] max-md:mt-10">
          <div className="w-full">Copyright @2024</div>
        </div>
      </div>
    </aside>
  );
}

export default SideBar;
