/**
 * This code was generated by Builder.io.
 */
import React from "react";

export default function CardInput({ label, id, placeholder, withIcon }) {
  return (
    <div className="flex flex-wrap gap-10 justify-between items-start mt-4 w-full text-base text-neutral-800 max-md:max-w-full">
      <div
        className={`flex flex-col ${
          withIcon ? "" : ""
        }`}
      >
        <label htmlFor={id} className="font-bold leading-none opacity-80">
          {label}
        </label>
        <div
          className={`flex ${
            withIcon ? "gap-10" : "flex-col"
          } justify-center px-5 py-2.5 mt-3 max-w-full rounded-lg bg-stone-50 border `}
        >
          <input
            type="text"
            id={id}
            aria-label={label}
            placeholder={placeholder}
          
          />
        
        </div>
      </div>
    </div>
  );
}
