/**
 * This code was generated by Builder.io.
 */
import React from "react";

export default function PayWithOptions() {
  return (
    <section className="flex flex-col mt-9 w-full max-w-[720px] max-md:max-w-full">
      <button className="overflow-hidden gap-1 self-stretch px-4 py-3.5 w-full text-xs italic tracking-tight leading-none text-white bg-indigo-600 rounded min-h-[44px]">
        Pay with <span className="italic font-extrabold">UPI</span>
      </button>
      <button className="flex overflow-hidden flex-wrap gap-1 justify-center items-center px-4 py-3.5 mt-2.5 w-full text-xs tracking-tight leading-none text-blue-900 bg-amber-400 rounded min-h-[44px]">
        <span className="self-stretch my-auto">Buy with</span>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/269e40e27255869f834ae5a8a058987f0171821200e1795bcfdbb2217efb935f?apiKey=b4d1b9e87b084579b1e2475047caf617&"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto aspect-[4.29] w-[60px]"
        />
      </button>
      <button className="flex overflow-hidden justify-center items-center px-4 py-2.5 mt-2.5 w-full bg-black rounded min-h-[44px]">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/167ab23d28acef8d59b7cb0a00a98feb5a2aa32bcbc07fc7afb333c6600c48ee?apiKey=b4d1b9e87b084579b1e2475047caf617&"
          alt=""
          className="object-contain self-stretch my-auto aspect-[2.46] w-[59px]"
        />
      </button>
      <div className="flex overflow-hidden flex-col justify-center mt-2.5 w-full h-11 rounded max-md:max-w-full">
        <div className="flex gap-1 justify-center items-center px-4 pt-4 pb-2 w-full max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8ec1f5dbdcf380a50ef48f0e586c52ef76209ac01ffacf61bbe8f9c7eed9d00d?apiKey=b4d1b9e87b084579b1e2475047caf617&"
            alt=""
            className="object-contain self-stretch my-auto aspect-[5.08] w-[127px]"
          />
        </div>
        <div className="flex w-full bg-black min-h-[3px] max-md:max-w-full" />
      </div>
      <button className="flex overflow-hidden flex-wrap gap-1 justify-center items-center px-4 py-3.5 mt-2.5 w-full text-sm tracking-tight leading-none text-white bg-black rounded min-h-[44px]">
        <span className="self-stretch my-auto">Pay with</span>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/9331e71a47a1b0c6abb57de86ff4d7f3299578c8b04f59a78817024e33f54a77?apiKey=b4d1b9e87b084579b1e2475047caf617&"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto aspect-[2.44] w-[39px]"
        />
      </button>
    </section>
  );
}
